[Feat/#24] 인터벌 삭제, 리프레쉬, 업데이트 구현
TEAM-ALOM/interest-iOS pull request #26
Opened 2024-01-16 12:49 UTC by beanbeen0

## PR 요약
1. addScreen에서 저장 버튼을 누르면 intervalListViewModel이 리프레쉬 됩니다.
2. 수정 버튼을 누르면 addSreen이 열립니다.

#### 📌 변경 사항

##### ✅ PR check list
편집 버튼을 눌렀을 때 addIntervalScreen 띄우는 부분 피드백 받고 싶습니다 !! 
이부분 시트가 intervalListScreen에 속해 있어서 먼저 DI컨테이너와 라우터를 넘겨 받아 객체를 새로 생성하는 방식을 생각했었는데 코드가 지저분 해지는 것 같아,, intervalListViewmodel의 라우터를 사용하고자 했습니다,,! 

+) 뷰모델을 사용해서 뷰를 반환하고자 하니 intervalListViewmodelWithRouter 에서 메소드 오버라이딩할 때 문제가 생겨서 우선 WithRouter뷰모델을 사용했습니다,, 

#### Linked Issue

close #24

2024-01-16 13:14 UTC, mooyoung2309 requested changes
사실 제가 이 프로젝트를 리드를 하고 있는데요, 제대로 알아보지도 않고 마구잡이로 개발을 했었음을 반성합니다. 실제로 설계 자체가 부족했네요, 특히 부모 자식간의 액션을 주고 받는 상황을 고려하지 않았어요. 이부분은 저도 공부를 하고 수정을 다시 해보고 싶네요. 어쩌면 많은 수정사항이 발생할 수 있어보입니다. rebase를 해야하는 상황도 있을 것 같은데, 제가 차근차근 알려드리겠습니다. 리뷰는 답변과 반영해주세요! 

고생하셨습니다 :> 수정한다음 re - request 해주세요! 리뷰 다시 등록해주시면 보겠습니다.

2024-01-16 13:14 UTC, annapo99 commented on Projects/App/WatchExtension/Sources/DIContainer/IntervalDIContainer.swift
> +        let intervalRepository = IntervalRepository(dataSource: intervalDataSource)
ViewModelWithRouter을 리턴 하는 것보다 ViewModel을 리턴하는 것이 나은 이유는, ViewModel은 Interface로서 사용되기 때문입니다. ViewModelWithRouter은 누구도 몰라도 됩니다. 로직을 처리하는 부분만 알면 되기 때문에 리턴하지 않아도 된다고 생각합니다. 어떤 이유로 수정을 했는지 궁금합니다 :>

2024-01-16 13:14 UTC, annapo99 commented on Projects/Presentation/Sources/Flows/Interval/IntervalDIContainerInterface.swift
> +    func intervalDetailDependencies(intervalRouter: IntervalRouter, intervalItem: IntervalModel) -> IntervalDetailViewModelWithRouter
위와 동일한 피드백입니다!

2024-01-16 13:14 UTC, annapo99 commented on Projects/App/WatchExtension/Sources/DIContainer/IntervalDIContainer.swift
> +        let intervalRepository = IntervalRepository(dataSource: intervalDataSource)
https://medium.com/@mooyoung2309/swiftui-mvvm-clean-architecture-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-2-4662ceae0572 해당 내용으로 글을 쓴게 있는데 천천히 읽어보시면 좋을 것 같아요.

2024-01-16 13:14 UTC, annapo99 commented on Projects/Presentation/Sources/Flows/Interval/ViewModel/IntervalViewModel.swift
> +    }
이런식으로 우선, list의 screen을 강하게 참조하는 상황은 좋지 못합니다. 왜냐면 IntervalViewModel은 그 자체로 독립적이어야 하지만, IntervalListScreen에 의존이 발생하기 때문에 외부의 IntervalListScreen의 ViewModel의 변경 사항에 제약을 받습니다. 따라서, 이부분은 어떻게 해결하면 좋을지 생각하는 것이 중요했는데 제 생각에는 자식의 액션이 부모로 전달하게 하는 것이 핵심이었습니다. 그래서 @Environment 키워드를 사용해서 해결하는 것이 어떨지 싶었습니다.

https://developer.apple.com/documentation/swiftui/environment 저희가 지금 사용하는 ViewModel은 Screen(View) 내부에서 이런 방향으로 수정이 되어야 할것같아요.

2024-01-16 13:14 UTC, mooyoung2309 commented on Projects/Presentation/Sources/Interval/Add/AddIntervalViewModel.swift
> +
https://developer.apple.com/documentation/swiftui/migrating-from-the-observable-object-protocol-to-the-observable-macro 저도 오늘 알게 되었는데요. ObservableObject를 Observable 매크로로 마이그레이션 하는 작업이 필요해보입니다. 또한 State Property wrapper는 View(SwiftUI) 내부에서 사용해야 합니다.

2024-01-16 13:14 UTC, mooyoung2309 commented on Projects/Presentation/Sources/Interval/Add/AddIntervalViewModel.swift
> +        self.restingTime = intervalItem.restingSecondTime
이부분은 제가 생각해보았는데요, 그냥 intervalItem을 직접적으로 사용하는 것은 어떨지?! 생각을 해보았습니다.

2024-01-16 13:14 UTC, mooyoung2309 commented on Projects/Presentation/Sources/Interval/Add/AddIntervalViewModel.swift
> +        }
이런 상황에서 강제 언래핑은 피해야 합니다. 왜냐면 런타임 시에 발생할 수 있기 때문입니다. 강제 언래핑을 무조건 피해야 하는 것은 아니지만, 이 시점에서는 selectedItemId가 비어있는 상황이 발생할 수 있기 때문입니다. (인간의 실수도 포함)

2024-01-16 13:14 UTC, mooyoung2309 commented on Projects/Presentation/Sources/Interval/Add/Picker/BurningRestingPicker.swift
> +//        print(totalTime)
주석 제거 해주시면 감사하겠습니다:>

2024-01-16 13:18 UTC, YugyeongChoi requested changes
수고하셨어요! 
피드백 후 저도 다시 re-request 해주시면 코드 보겠습니다!!

2024-01-16 13:18 UTC, YugyeongChoi commented on Projects/App/WatchExtension/Sources/DIContainer/IntervalDIContainer.swift
>          let intervalDataSource = IntervalDataSource()
여기서 ViewModel을 ViewModelWithRouter로 바꾼 이유가 메소드 오버라이딩 문제 때문인거죠?? 혹시 어떤 문제때문에 이렇게 바꾸셨는지 궁금합니다!

2024-01-16 13:18 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Interval/Add/AddIntervalViewModel.swift
> +
init이 중복되는거 같아요!! 앞의 init은 지워도 되지 않을까 합니당

2024-01-17 09:42 UTC, beanbeen0 commented on Projects/App/WatchExtension/Sources/DIContainer/IntervalDIContainer.swift
> +        let intervalRepository = IntervalRepository(dataSource: intervalDataSource)
```
public class IntervalListViewModelWithRouter: IntervalListViewModel {
    private var router: IntervalRouter
    
    override func editIntervalScreen(selectedItem: IntervalModel) -> some View {
        return router.sheetScreen(route: .editInterval(selectedItem))
    }
}

public class IntervalListViewModel: ObservableObject {
    func editIntervalScreen(selectedItem: IntervalModel) -> some View { }
}
```
시트로 addIntervalScreen을 띄우기 위해 라우터를 사용해 위와 같이 해당 뷰를 반환해주는 함수를 작성하였습니다만,, 오버라이딩시에 Method does not override any method from its superclass과 맡은 에러를 맞딱트려 해결하는 과정에서 수정하게 되었습니다

2024-01-18 09:16 UTC, ShapeKim98 approved these changes
수고하셨습니다! pr 올라온지 모르고 있다가 이제 봤어요..!!
SwiftUI + MVVM + CleanArchitecture는 누가 이거다! 라고 결론 내린게 없기 때문에.. 저도 공부를 더 하고 코드 수정도 많이 해야할 것 같아요. 
그리고 사실 SwiftUI 자체가 View와 ViewModel을 합쳐놓은듯한 프레임워크라 SwiftUI와 MVVM은 서로 잘 맞다고는 못할것 같습니다.(개인적인 생각) 
그렇기 때문에 SwiftUI에서는 TCA가 핫한게 아닐까...라고 생각해요..ㅎㅎ

2024-01-18 09:16 UTC, ShapeKim98 commented on Projects/Presentation/Sources/Flows/Interval/IntervalRouter.swift
> +    }
sheet나 full cover screen 같은 것들은 새로운 navigation을 사용하게 되는데, 그러면서 navigation path 또한 새로운 path로 관리를 해야한다고 생각합니다. 그렇기 때문에 저희가 참고하는 예제에서도 
https://github.com/mui-z/GithubRepoSearcher-FlowRouter/blob/main/GithubRepoSearcherPackage/Sources/GithubRepoSearcherPackage/UI/Screen/Search/DetailScreen.swift
 전용 라우터를 하나 만든 모습을 볼 수 있어요
그렇기 때문에 IntervalRouter에서 sheet를 관리하기 보단, 별도의 라우터를 생성하는게 좋아보입니다.

2024-01-18 09:16 UTC, ShapeKim98 commented on Projects/Presentation/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> -        .sheet(isPresented: $viewModel.showEditIntervalView, content: {
그냥 문뜩 생각이 들었는데.. sheet 트리커를 ViewModel이 아니라 라우터에서 구현하고 sheet modifier를 Root뷰 단에서 선언하는게 어떨까 싶었습니다. 그러면서 부모 자식 뷰간 함수 전달도 라우터가 담당하게 하면 좋지 않을까.. 라는 생각...? 구체적인 방법은 좀 더 고민을 해봐야 할 것 같아요

2024-01-18 10:04 UTC, annapo99 commented on Projects/Presentation/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> -        .sheet(isPresented: $viewModel.showEditIntervalView, content: {
어떤 흐름에서 생각을 하셨는지 공감이되는것같아요. 그런데 문제는 Root가 너무많은 책임을 지지 않을까 생각합니다..!

2024-01-18 10:59 UTC, ShapeKim98 commented on Projects/Presentation/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> -        .sheet(isPresented: $viewModel.showEditIntervalView, content: {
> 어떤 흐름에서 생각을 하셨는지 공감이되는것같아요. 그런데 문제는 Root가 너무많은 책임을 지지 않을까 생각합니다..!

하긴.. 그거대로 또 문제겠네요...

2024-01-19 14:48 UTC, merged