[Feat/#32] 코드 정리 및 리펙토링
TEAM-ALOM/interest-iOS pull request #33
Opened 2024-02-03 13:26 UTC by mooyoung2309

## PR 요약

#### 📌 변경 사항

##### ✅ PR check list

#### Linked Issue

close #32

2024-02-04 08:27 UTC, YugyeongChoi approved these changes
수고하셨습니다!! 저도 Presentation이 좀 무거워지는거 같다고 생각은 했었는데 이렇게 바뀌니 좋네요. 그리고 DIContainer가 삭제되니 코드가 좀 더 직관적으로 바뀐거 같아 좋습니다!

궁금한 점이 있는데, 그러면 이제 Presentation는 재사용가능한 UI, Feature는 이에 필요한 기능을 모아두는 곳이라고 생각하고 Presentation에 UI를 하나씩 옮겨가면 되는걸까요?

그리고, Data 레이어가 Presentation의 하위에 있는 것에 저도 찬성합니다! 
그런데 아직 동일한 레이어에 있는거같아, 이것도 반영해 주시면 좋을거같습니당!

2024-02-04 08:27 UTC, YugyeongChoi commented on Projects/Feature/Sources/DependencyValues+UseCase.swift
> +}
이 코드는 UseCase를 Feature에서 사용하기 위함인가요?!

2024-02-04 08:27 UTC, YugyeongChoi commented on Projects/Feature/Sources/Flows/Interval/ViewModel/IntervalViewModel.swift
> +            }
그렇다면 ListScreen이 @State로 관리되니까, 리프레쉬 할 이유가 없는걸까요..??

2024-02-04 12:18 UTC, ShapeKim98 requested changes
수고하셨습니다! 전반적으로 본인의 tca사랑(?)이 잘 느껴지는 코드였던거 같습니다 ㅋㅋㅋㅋ

2024-02-04 12:18 UTC, ShapeKim98 commented on Projects/Data/Sources/Interval/DataSource/IntervalDataSource.swift
> +public extension DependencyValues {
이거 tca에 내장 되어있는줄 알았는데, 따로 존재한다는걸 처음 알았네요...

2024-02-04 12:18 UTC, ShapeKim98 commented on Projects/Feature/Project.swift
> +let featureTarget = Target(
나중에 기능도 많아지고, 프로젝트가 좀 더 복잡해지면 feature를 더 쪼개는 것도 좋을 것 같아요!

2024-02-04 12:18 UTC, ShapeKim98 commented on Projects/Feature/Sources/Flows/Interval/IntervalRouter.swift
> +        nextNavigationRoute?.nextView
![Simulator Screenshot - iPhone 15 Pro - 2024-02-04 at 21 01 37](https://github.com/TEAM-ALOM/interest-iOS/assets/108233361/526061d9-8cde-4609-82eb-ecf6666cd7e1)
저는 다음 뷰로 넘어갈때 이런 화면이 나와서 원인을 찾아본 결과, nextNavigationRoute가 옵셔널로 선언 되어서 그렇다는 것을 확인했는데요..! 이 nextNavigationRoute를 논옵셔널로 하는게 좋을 것 같아요!

2024-02-04 12:18 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/Add/AddIntervalViewModel.swift
> +    public enum Action {
저는 여기보고 얼마나 tca를 사랑하셨는지 너무 확 느껴져서 빵 터졌다랄까 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-02-04 12:27 UTC, annapo99 commented on Projects/Feature/Sources/Flows/Interval/IntervalRouter.swift
> +        nextNavigationRoute?.nextView
저도 이거 찾다가 찾다가 

[fix: navigation stack 이동안하는 버그 픽스](https://github.com/TEAM-ALOM/interest-iOS/pull/35/commits/af1ab5fef3fe4c4ce0f97cd3d5b49259800804ae) 요기서 해결했습니다! 감사합니다

2024-02-04 12:28 UTC, mooyoung2309 commented on Projects/Data/Sources/Interval/DataSource/IntervalDataSource.swift
> +public extension DependencyValues {
DI 라이브러리 중에 꽤 괜찮은 편이라고 조언을 듣고왔습니다.. ㅎㅎ 저도 사실 요것만 따로 써봤는데요.. liveValue 이친구가 문제를 일으켜서, feature에서 주입 하는 방향으로 수정하였습니다

2024-02-04 12:28 UTC, ShapeKim98 commented on Projects/Feature/Sources/Flows/Interval/IntervalRouter.swift
> +        nextNavigationRoute?.nextView
> 저도 이거 찾다가 찾다가
> 
> [fix: navigation stack 이동안하는 버그 픽스](https://github.com/TEAM-ALOM/interest-iOS/pull/35/commits/af1ab5fef3fe4c4ce0f97cd3d5b49259800804ae) 요기서 해결했습니다! 감사합니다

앗..!

2024-02-04 12:29 UTC, mooyoung2309 commented on Projects/Feature/Project.swift
> +let featureTarget = Target(
감사합니다. 저는 사실 쪼개는 것을 좋아해요. 아주 잘게 쪼개보고 싶네요. 아자잣

2024-02-04 12:30 UTC, mooyoung2309 commented on Projects/Feature/Sources/Interval/Add/AddIntervalViewModel.swift
> +    public enum Action {
감사합니다. 저는 tca를 좋아해요. 코드로 사람을 웃기기 쉽지 않은데 제가 그것을 해냈네요.

2024-02-04 12:31 UTC, mooyoung2309 commented on Projects/Feature/Sources/DependencyValues+UseCase.swift
> +}
네 맞아요. 문제는 UseCase는 Data에 있는 Repository를 주입받아햐 하는데, Domain에서는 DI를 못하고, Data와 Domain을 모두 아는 레이어인 Feature 레이어에서 주입을 하였습니다

2024-02-04 12:32 UTC, mooyoung2309 commented on Projects/Feature/Sources/Flows/Interval/ViewModel/IntervalViewModel.swift
> +            }
아 그거는 지웠어요. ListScreen의 ViewModel이 State로 관리되기 때문에 ViewModel은 Observable 프로퍼티를 채택하기 때문에 내부에 있는 intervalItems의 변동이 있으면 해당 뷰를 리프레시 해주는 것입니다

2024-02-06 05:02 UTC, ShapeKim98 approved these changes
approve

2024-02-07 12:45 UTC, merged