[Feat/#36] Interval Add, Edit, Delete 의 상세 구현
TEAM-ALOM/interest-iOS pull request #38
Opened 2024-02-11 10:31 UTC by YugyeongChoi

## PR 요약
1. Add, Edit, List, Detail의 재사용 가능한 UI를 Presentation으로 옮겼습니다.
2. Add와 Edit을 분리하였습니다. 
3. edit 로직을 구현했습니다.

#### 📌 변경 사항

##### ✅ PR check list
IntervalListIPhoneScreen과 IntervalInfoCellView를 합치고 싶었습니다. 
그런데cellOffsetX가 IntervalInfoCellView마다 하나씩 존재해야 하고, tool과 cell에서 함께 공유해야 하기 때문에 하나의 뷰로(원래 그대로) 분리했습니다. 혹시 더 좋은 방법이 있다면 피드백 해주세요!

#### Linked Issue
close #36

#### Preview

https://github.com/TEAM-ALOM/interest-iOS/assets/122093721/8335e3bd-2e1f-4760-8026-a1e3ef04072f

2024-02-11 12:42 UTC, mooyoung2309 reviewed
고생하셨습니다! 리뷰 다시 요청주시면 다시 확인하겠습니다!

2024-02-11 12:42 UTC, mooyoung2309 commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
전체적인 줄간격, extension, 띄어쓰기를 변경한 코드 입니다. 이런식으로 변경되면 좋을 것 같아요! (but.. 동작 확인 안해봤음.)

```swift
import Foundation
import SwiftUI
import SwiftData
import SharedDesignSystem
import Domain
import Presentation

public struct AddIntervalScreen: View {
    @State var viewModel: AddIntervalViewModel
    
    public init(viewModel: AddIntervalViewModel) {
        self._viewModel = .init(wrappedValue: viewModel)
    }
    
    public var body: some View {
        NavigationStack {
            containerView
                .padding(.horizontal, 30)
                .padding(.top, 10)
                .navigationTitle(
                    "인터벌 추가"
                )
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .topBarLeading) {
                        Button(action: {
                        }, label: {
                            Text("취소")
                        })
                    }
                    ToolbarItem(placement: .topBarTrailing) {
                        Button(action: {
                            viewModel.tapSaveButton()
                        }, label: {
                            Text("저장")
                        })
                    }
                }
        }
    }
}

private extension AddIntervalScreen {
    private var containerView: some View {
        ScrollView {
            nameView
            exercisePickerView
            repeatCountPickerView
            burningRestingPickerView
            Spacer()
        }
    }
    
    private var nameView: some View {
        VStack{
            HStack{
                Text("이름")
                    .fontWeight(.semibold)
                Spacer()
            }
            TextField("달리기 인터벌", text: $viewModel._intervalItem.title)
                .padding(.all, 12)
                .cornerRadius(10)
            
        }
    }
    private var exercisePickerView: some View {
        HStack{
            ExercisePickerView(
                selectedExerciseType: $viewModel._intervalItem.exerciseType
            )
        }
        .padding(.vertical, 10)
    }
    
    private var repeatCountPickerView: some View {
        VStack{
            RepeatPicker(
                isRepeat: false,
                repeatCount: $viewModel._intervalItem.repeatCount
            )
        }
    }
    
    private var burningRestingPickerView: some View {
        VStack{
            BurningRestingPicker(
                isBurning: true,
                heartType: $viewModel._intervalItem.burningHeartIntervalType,
                totalTime: $viewModel._intervalItem.burningSecondTime
            )
            
            BurningRestingPicker(
                isBurning: false,
                heartType: $viewModel._intervalItem.restingHeartIntervalType,
                totalTime: $viewModel._intervalItem.restingSecondTime
            )
        }
    }
}

```

2024-02-11 12:42 UTC, mooyoung2309 commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
>      @Environment(\.colorScheme) var colorScheme: ColorScheme
dismiss는 router로 관리되고 다크모드는 디자인시스템으로 관리되기 때문에 두 코드는 필요없어보입니다.

2024-02-11 12:42 UTC, annapo99 commented on Projects/Feature/Sources/Interval/Add/AddIntervalViewModel.swift
> +    private var intervalItemOrNil: Binding<IntervalEntity>?
```swift
public var intervalEntity: IntervalEntity
```

이것 빼고는 모두 필요 없어보이는 친구들입니다!

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Add/Picker/BurningRestingPicker.swift
> +                    ForEach(0..<60) { i in
요 Picker의 경우에는 datePicker을 활용하는 방법은 없었을까요? 커스텀을 안해도 된다면 기존의 컴포넌트를 사용하는 것이 좋아보입니다!

2024-02-11 12:42 UTC, mooyoung2309 commented on Projects/Presentation/Sources/Add/Picker/BurningRestingPicker.swift
> +                    Text("5구간 (176BPM~)").tag(HeartIntervalType.five)
```swift
// 동일 파일 내
    Picker("", selection: selection) {
                    ForEach(HeartIntervalType.allCases, id: \.self) { type in
                        Text(type.title).tag(type)
                    }
                }

private extension HeartIntervalType {
    var title: String {
        switch self {
        case .one: "1구간 (123~134BPM)"
        case .two: "2구간 (135~148BPM)"
        case .three: "3구간 (149~162BPM)"
        case .four: "4구간 (163~175BPM)"
        case .five: "5구간 (176BPM~)"
        }
    }
}

```

```swift
// 기존 엔티티에 CaseIterable 채책
public enum HeartIntervalType: CaseIterable {
    case one
    case two
    case three
    case four
    case five
    
    public var heartTypeName: String {
        switch self {
        case .one: "1구간"
        case .two: "2구간"
        case .three: "3구간"
        case .four: "4구간"
        case .five: "5구간"
        }
    }
}

```

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Add/Picker/BurningRestingPicker.swift
> +                    Text("5구간 (176BPM~)").tag(HeartIntervalType.five)
이런식으로 변경 가능해 보이고, heartTypeName은 사용중이지 않다면 제거 해도 좋아보입니다

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Add/Picker/ExercisePicker.swift
: 콜론 사이에 띄어쓰기 없애주세요

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Add/Picker/RepeatPicker.swift
이것도 제거 부탁드립니다!

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Add/Picker/RepeatPicker.swift
콜론!

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Cell/IntervalRecordCellView.swift
>      }
이부분은 엔티티 명이 변경되어서 수정되는 것이죠?

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Cell/IntervalInfoCell.swift
> +    @Binding var intervalEntity : IntervalEntity
바인딩 처리할 이유가 있을까요? 단순히 받아서 보여질 용도면 그대로 받아서 띄워주기만 하면 좋을 것 같아요. 그리고 오히려 CellX 값을 위에서 전달받아서 사용하면 애니메이션도 그대로 사용할 수 있어보입니다 : D

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Cell/IntervalInfoCell.swift
> +    var restingMinute : Int
값을 저장해서 사용하기보다, 단순히 Text안에서 연산을 해서 넣어주는 것도 좋아보입니다. 그걸 함수로 빼서 해도 좋을 것 같네요.

2024-02-11 12:42 UTC, annapo99 commented on Projects/Presentation/Sources/Cell/IntervalInfoCell.swift
> +}
이친구는 public 인 이유가 있을까요? 그리고 줄내림 한번만 부탁드려요. 음 그리고.. 막 엄청 재사용성이 높지 않아보입니다. View 내부에 extension 함수로 있는게 좋아보여요.

2024-02-11 12:42 UTC, annapo99 commented on Projects/Feature/Sources/Interval/Add/AddIntervalViewModel.swift
> +    public var _intervalItem : IntervalEntity
네이밍 통일을 제안드려요. 그리고 안쓰이는 `IntervalModel`은 제거해주시면 감사하겠습니다

```swift
intervalEntity: IntervalEntity
```

2024-02-14 00:32 UTC, ShapeKim98 requested changes
수고하셨습니다! 더 좋은 코드들을 적으려고 고민한 흔적이 많이 보이는 코드였습니다!

2024-02-14 00:32 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
>                  .background(colorScheme == .dark ? Color.textColor25 : Color.textColor75)
음.. 이거는 colorScheme사용을 디자인시스템에서만 쓸 수 있도록 모디파이어를 하나 제작하겠습니다!

2024-02-14 00:32 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> +
list화면과 cell을 합치려고한 이유가 궁금해요!

2024-02-14 00:32 UTC, ShapeKim98 commented on Projects/Presentation/Sources/Add/Picker/RepeatPicker.swift
> 콜론!

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-02-14 00:32 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/Detail/IntervalDetailScreen.swift
> +                        IntervalRecordCellView(intervalRecordEntity: record)
👍

2024-02-14 00:32 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/Edit/EditIntervalViewModel.swift
> +    private var intervalEntity : Binding<IntervalEntity>
여기는 바인딩 처리가 필요 없을것 같아요.
intervalEntity의 정보는 여기서 변경하는게 아니라 SwiftData가 바꿔주는 거기 때문에, update 호출 후, 부모 액션 fetch를 호출하는 로직이 더 바람직 해보입니다.
그리고 이렇게 하면 사용자가 제목이나 시간을을 변경하다가 저장이 아닌 취소를 눌렀을 경우에는 값이 원래대로 돌아오지 않을 것 같아요.

2024-02-17 12:27 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
훨씬 깔끔하네요! 빌드 되는거 확인했습니다 수정할게요!

2024-02-17 12:33 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Add/Picker/BurningRestingPicker.swift
> +                    Text("5구간 (176BPM~)").tag(HeartIntervalType.five)
앗 네 !! extension은 좋아보입니다! 하지만 heartTypeName은 사용중이라 제거는 못할거같아요ㅜ!

2024-02-17 12:39 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
>      @Environment(\.colorScheme) var colorScheme: ColorScheme
넵!!

2024-02-17 12:39 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Add/Picker/ExercisePicker.swift
넵ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-02-17 14:34 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Cell/IntervalRecordCellView.swift
>      }
명이 변경되기 보다 intervalRecordModel -> intervalRecordEntity로 바꾸어서 수정되었습니다!

2024-02-17 14:43 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/Add/AddIntervalScreen.swift
>                  .background(colorScheme == .dark ? Color.textColor25 : Color.textColor75)
헉 그러면 너무 감사하죠!! 😆 👍🏻

2024-02-17 14:54 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Add/Picker/BurningRestingPicker.swift
> +                    ForEach(0..<60) { i in
이 부분은 DatePicker가 한정적이라 이를 활용하는 방법이 딱히 없어 이렇게 했습니다! ㅜㅜ

2024-02-17 15:12 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> +
tool 부분이 viewModel을 호출해야해서 따로 Presentation으로 빼지않고 두었습니다. 
그런데 cellOffsetX이 cell에서만 변경이 되어서 tool이 cell의 하위뷰라고 생각했어요.
그래서 tool에 바인딩으로 cellOffsetX을 받으려고 하였는데 tool에서 viewModel을 호출해야 하기 때문에 IntervalListIPhoneScreen에 있어야 하고,, 그래서 바인딩 처리를 어떻게 해야할지 모르겠어서 일단 합쳐봤습니다..ㅜㅜ 혹시 더 좋은 방법이 있으면 피드백해주시면 감사하겠습니다!

2024-02-17 15:30 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Cell/IntervalInfoCell.swift
> +    @Binding var intervalEntity : IntervalEntity
넵 바인딩은 뺐습니다!
CellX의 값을 다루는게 아직 고민인데, 
IntervalListIPhoneScreen에서 tool 부분이 viewModel을 호출해야해서 따로 Presentation으로 빼지않고 두었습니다.
그런데 cellOffsetX이 cell에서만 변경이 되어서 tool이 cell의 하위뷰라고 생각했어요.
그래서 tool에 바인딩으로 cellOffsetX을 받으려고 하였는데 tool에서 viewModel을 호출해야 하기 때문에 IntervalListIPhoneScreen에 있어야 하고,, 그래서 바인딩 처리를 어떻게 해야할지 모르겠어서 일단 합쳐봤습니다..ㅜㅜ 혹시 더 좋은 방법이 있으면 피드백해주시면 감사하겠습니다!

2024-02-17 15:33 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/Edit/EditIntervalViewModel.swift
> +    private var intervalEntity : Binding<IntervalEntity>
헉 그렇네요..! 이 부분은 생각치 못했는데 감사합니다!

2024-02-18 02:22 UTC, YugyeongChoi commented on Projects/Presentation/Sources/Cell/IntervalInfoCell.swift
> +}
넵 수정했습니다!

2024-02-18 06:36 UTC, mooyoung2309 approved these changes
고생하셨습니다!!

2024-02-19 04:00 UTC, ShapeKim98 commented on Projects/Feature/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> +
> tool 부분이 viewModel을 호출해야해서 따로 Presentation으로 빼지않고 두었습니다. 그런데 cellOffsetX이 cell에서만 변경이 되어서 tool이 cell의 하위뷰라고 생각했어요. 그래서 tool에 바인딩으로 cellOffsetX을 받으려고 하였는데 tool에서 viewModel을 호출해야 하기 때문에 IntervalListIPhoneScreen에 있어야 하고,, 그래서 바인딩 처리를 어떻게 해야할지 모르겠어서 일단 합쳐봤습니다..ㅜㅜ 혹시 더 좋은 방법이 있으면 피드백해주시면 감사하겠습니다!

일단 Presentation으로 빼야하는건 맞습니다.
그래서 이부분에 대해 조금 생각해보았는데요, 저는 두가지 방법이 떠올랐습니다.

첫번째로, ViewModel의 명세서가 되는 protocol을 만들어 DIP를 발생시키는 방법이 있고,
두번째로, cell에 ViewModel 의존을 피하고, 필요한 action만 넘겨주는 방법이 있습니다.

첫번째 방법은 저희가 WithRouter로 Router를 분리 시켜 놓았기 때문에, 충분히 가능할 것으로 생각되며, protocol 만드는게 조금 귀찮을 수 는 있으나, 유지 보수성이 좋을 것으로 생각됩니다.

두번째 방법은 구현은 편하지만, 부모뷰의 액션을 직접 참조하기 때문에, 기능추가나 필요한 action이 있을 경우 수정하기 위한 Cell뷰 리펙토링이 필요하여 유지보수성이 떨어질 것으로 생각됩니다.

클린아키텍쳐의 본질적인 목적은, 두번째 방법과 같은 이슈를 피하기 위해서이기 때문에, 저는 첫번째 방법이 괜찮을 것 같다고 생각합니다!

2024-02-19 04:01 UTC, ShapeKim98 approved these changes
수고하셨습니다!

2024-02-19 06:04 UTC, YugyeongChoi commented on Projects/Feature/Sources/Interval/List/Screen/iOS/IntervalListIPhoneScreen.swift
> +
그러면 혹시 IntervalListViewModelProtocol을 Feature에서 만들어보았는데, Presentation의 IntervalInfoCell에서 import Feature로 의존성을 주입하는게 맞을까요..??

2024-02-19 07:08 UTC, merged